### ISSUE TITLE
관계 설정으로 인한 삭제 프로세스 미작동

### ISSUE THREAD

**Issue by nineruler** [psyy1204/MedicalRecord#1]
commit 2af167a

관계 설정으로 인해 병원, 증상 삭제가 되지 않는다고 했는데,
경험으로 알고 있겠지만 관계가 있는 경우 데이터를 child 수준에서부터 삭제해야함

예를 들어 현재 진료기록을 등록하기 위해서는 회원, 병원, 증상, 처방-약 등의 엔티티와 관계된 데이터가 생성됨
이 상태에서 회원, 병원, 증상, 처방 등의 데이터를 삭제하려고 하면 에러 발생
-> 진료 기록에서는 해당 데이터들의 관계를 맺고 있는데 그 데이터를 삭제하면 안되기 때문

그렇기 때문에 병원을 삭제하고자 한다면 진료기록부터 삭제해야 함

이론적으로는 그렇지만 실제로 삭제처리가 필요한 경우가 있음
이런 경우에는 삭제여부 컬럼을 추가하여 해당 데이터는 남아 있으나 관리 시에 필터링 할 수 있도록 하는 방법이 있음

데이터의 실제 삭제는 현업에서도 보수적으로 접근하기 때문에 CRUD 중에서 삭제 기능은 우선순위가 가장 떨어짐

**Comment by psyy1204** [comment]
넹 감사합니다!
